SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (1, N'iphone', 1, 5, 500, 321, 1, 100)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (2, N'ipad', 1, 5, 550, 153, 1, 100)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (3, N'ipod', 1, 5, 450, 531, 1, 100)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (4, N'galaxy note', 1, 5, 550, 513, 2, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (5, N'galaxy s', 1, 5, 500, 551, 2, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (6, N'galaxy tab', 1, 5, 550, 651, 2, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (7, N'galaxy note tab', 1, 5, 600, 456, 2, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (8, N'dell laptop', 1, 5, 700, 531, 4, 10)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (9, N'dell pc', 1, 5, 750, 513, 4, 10)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (10, N'hp pc', 1, 5, 700, 153, 3, 20)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (11, N'hp laptop', 1, 5, 650, 561, 3, 20)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (12, N'salt', 0.5, 10, 2, 500, 5, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (13, N'rice', 0.5, 10, 3, 123, 5, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (14, N'spaghetti', 0.5, 5, 1.5, 132, 5, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (16, N'sugar', 0.5, 5, 2.5, 89, 5, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (17, N'burger', 3, 15, 7, 32, 6, 10)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (18, N'Kentucky', 2, 10, 10, 53, 6, 20)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (19, N'pizza', 4, 10, 10, 34, 6, 20)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (20, N'beef', 0.5, 5, 15, 23, 8, 15)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (21, N'camel', 0.5, 5, 13, 37, 8, 10)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (22, N'sheep', 0.5, 5, 20, 10, 8, 20)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (23, N'jacket', 1, 5, 30, 5, 9, 5)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (25, N'shirt', 1, 5, 20, 65, 9, 5)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (26, N'shoes', 1, 10, 35, 13, 9, 5)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (27, N'potato', 0.25, 5, 2, 30, 10, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (28, N'tomato', 0.25, 5, 1.5, 20, 10, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (29, N'grap', 0.25, 5, 1, 21, 10, 50)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (30, N'antibiotic', 1, 20, 8, 65, 7, 100)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (31, N'panadol', 1, 20, 10, 18, 7, 100)
INSERT INTO [dbo].[Products] ([ProductId], [ProductName], [QuantityPerUnit], [ReorderLevel], [UnitPrice], [UnitsInStock], [SupplierId], [UnitsOnOrder]) VALUES (32, N'dettol', 0.25, 10, 5, 32, 7, 25)
SET IDENTITY_INSERT [dbo].[Products] OFF
